[project]
name = "geolab"
version = "0.1.0"
description = "Tool for geodetic calculations"
readme = "README.md"
authors = [
    { name = "Oguzb", email = "hoguzbolat@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "scipy>=1.18.1",
]

[project.scripts]
geolab = "geolab:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
